### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by SRGOM** [jeffreyolchovy/sbt-check#1]
I added the said lines (resolver + dependency) both int the global `plugings.sbt` and `project/plugins.sbt` but resolution failed in both cases.

**Comment by jeffreyolchovy** [comment]
Sorry, didn't see this until now. Fixed by https://github.com/jeffreyolchovy/sbt-check/commit/0e3182a0a6c98b1ba80b59fa8cbed2ffb49e9338.
