### ISSUE TITLE
Link to sbt-plugin-releases

### ISSUE THREAD

**Issue by laughedelic** [jeffreyolchovy/sbt-check#3]
Could you [link your bintray repo](http://www.scala-sbt.org/release/docs/Bintray-For-Plugins.html#Linking+your+package+to+the+sbt+organization) to [sbt-plugin-releases](https://bintray.com/sbt/sbt-plugin-releases)? 
This would make the `resolvers += Resolver.bintrayIvyRepo("jeffreyolchovy", "sbt-plugins")` resolver unnecessary for the users of your plugin.

**Comment by jeffreyolchovy** [comment]
It should already be there starting from the 0.1.1 release on Oct 21 2017.

**Comment by laughedelic** [comment]
Thanks!
